using System.Text;
using Vex.TimelineSmith.Ir;
using Vex.TimelineSmith.Runtime;

namespace Vex.TimelineSmith.Compiler;

public static class Emitter
{
    public sealed record CompileResult(
        TimelineDocument Document,
        TimelineTables Tables,
        string AgentSource,
        string ProgramSource);

    public static IrResult<CompileResult> CompileFile(string irPath)
    {
        var loaded = TimelineLoader.LoadFile(irPath);
        if (!loaded.IsSuccess)
        {
            return IrResult<CompileResult>.Fail(loaded.Errors);
        }

        return IrResult<CompileResult>.Ok(Compile(loaded.Value!));
    }

    public static CompileResult Compile(TimelineDocument doc)
    {
        var tables = TimelineTables.FromDocument(doc);
        var agent = EmitAgent(doc, tables);
        var program = EmitProgram(doc.Id);
        return new CompileResult(doc, tables, agent, program);
    }

    public static void WriteToDirectory(CompileResult result, string outDir)
    {
        Directory.CreateDirectory(outDir);
        File.WriteAllText(Path.Combine(outDir, $"{Sanitize(result.Document.Id)}Agent.g.cs"), result.AgentSource);
        File.WriteAllText(Path.Combine(outDir, "Program.g.cs"), result.ProgramSource);
        File.WriteAllText(Path.Combine(outDir, "tables.txt"), DumpTables(result.Tables));
    }

    private static string EmitAgent(TimelineDocument doc, TimelineTables tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by Vex.TimelineSmith.Compiler — do not hand-edit.");
        sb.AppendLine("using Vex.TimelineSmith.Ir;");
        sb.AppendLine("using Vex.TimelineSmith.Runtime;");
        sb.AppendLine();
        sb.AppendLine("namespace Vex.TimelineSmith.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public static class {Sanitize(doc.Id)}Factory");
        sb.AppendLine("{");
        sb.AppendLine("    public static TimelineTables CreateTables()");
        sb.AppendLine("    {");
        sb.AppendLine($"        // Document: {doc.Id}, tick_hz={doc.TickHz}, duration={doc.Director.Duration.Ticks}");
        sb.AppendLine("        // Prefer loading IR at tool time; this stub documents the lower shape.");
        sb.AppendLine("        throw new System.InvalidOperationException(");
        sb.AppendLine("            \"Load IR via TimelineLoader and TimelineTables.FromDocument in Phase 1 harness.\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static TimelineAgent CreateAgent(TimelineTables tables) => new(tables);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine(DumpTablesAsComment(tables));
        return sb.ToString();
    }

    private static string EmitProgram(string id)
    {
        return $$"""
            // <auto-generated />
            // Sample harness: load IR beside this project and tick.
            using Vex.TimelineSmith.Ir;
            using Vex.TimelineSmith.Runtime;

            var ir = args.Length > 0 ? args[0] : "light_attack.timeline.yaml";
            var loaded = TimelineLoader.LoadFile(ir);
            if (!loaded.IsSuccess)
            {
                foreach (var e in loaded.Errors) Console.Error.WriteLine(e);
                return 1;
            }

            var tables = TimelineTables.FromDocument(loaded.Value!);
            var agent = new TimelineAgent(tables);
            var log = agent.RunScript(new ScriptOp[] { new ScriptOp.Play(), new ScriptOp.RunToEnd() });
            Console.Write(log.CanonicalString());
            return 0;
            """;
    }

    private static string DumpTables(TimelineTables t)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"id={t.Id} hz={t.TickHz} duration={t.DurationTicks} wrap={t.Wrap}");
        sb.AppendLine("boundaries:");
        foreach (var b in t.Boundaries)
        {
            sb.AppendLine($"  t={b.Tick} {b.Kind} {b.TrackName}/{b.ClipName}");
        }

        return sb.ToString();
    }

    private static string DumpTablesAsComment(TimelineTables t)
    {
        var lines = DumpTables(t).Split('\n').Select(l => "// " + l);
        return string.Join('\n', lines);
    }

    private static string Sanitize(string id)
    {
        var chars = id.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
        if (chars.Length == 0 || char.IsDigit(chars[0]))
        {
            return "T_" + new string(chars);
        }

        return new string(chars);
    }
}
